[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "STMSC"
authors = [{name = "Daijun Zhang", email = "djzhang@bliulab.net"}]
dynamic = ["version", "description"]
